# 网站基本设置
title: Hux Blog # 网站标题
SEOTitle: Jeff'Blog # SEO 优化使用的标题
header-img: img/home-bg.jpg # 首页头图路径
email: jeffsu470@gmail.com # 联系邮箱
description: "Learn to explore" # 网站描述
keyword: "DL, ML, NLP，Agent, RL" # 网站关键词
# url: "https://huangxuan.me"    # 网站网址（可选，如博客部署在子目录时设置 baseurl）
baseurl: "" # 基础路径（例如部署在 host/blog 则设置为 '/blog'）

# 发布设置
future: true # 是否允许发布未来日期的文章

# 社交账号设置
RSS: false # 是否开启 RSS
# weibo_username: huxpro # 微博用户名
# zhihu_username: huxpro # 知乎用户名
github_username: Jeff470sql # GitHub 用户名
# twitter_username: huxpro # Twitter 用户名
#facebook_username:  huxpro   # Facebook 用户名（已注释）
#linkedin_username:  firstname-lastname-idxxxx  # LinkedIn 用户名

# 构建设置
highlighter: rouge # 使用 rouge 高亮代码（GitHub Pages 推荐）
permalink: pretty # 链接格式使用 prettified 风格
paginate: 10 # 每页文章数量
exclude: # 构建时排除的文件或文件夹
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # 是否启用 anchor.js（标题锚点功能）
#timezone: CN             # 如有时区问题，可取消注释并设置中国时区

# 插件设置
plugins: [jekyll-paginate] # 启用 jekyll-paginate 分页插件

# Markdown 设置
markdown: kramdown # 使用 kramdown 解析 Markdown
kramdown:
  input: GFM # 使用 GitHub Flavored Markdown (GFM)
  syntax_highlighter_opts:
    span:
      line_numbers: false # 内联代码不显示行号
    block:
      line_numbers: true # 代码块显示行号
      start_line: 1 # 代码块行号从 1 开始

# 评论系统设置
disqus_username: Jeff # Disqus 评论系统用户名

# 网易云评论设置
netease_comment: false # 是否启用网易云评论

# 分析统计设置
# Baidu Analytics
# ba_track_id: [your track id]  # 百度统计账号（如需要请取消注释并设置）

# Google Analytics
ga_track_id: "UA-49627206-1" # Google Analytics 跟踪 ID，格式：UA-xxxxxx-xx
ga_domain: huangxuan.me # 分析域名

# 侧边栏设置
sidebar: true # 是否显示侧边栏
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta" # 侧边栏关于描述
sidebar-avatar: https://github.com/Jeff470sql.png # 侧边栏头像（需使用绝对 URL）

# 特色标签设置
featured-tags: true # 是否启用特色标签功能
featured-condition-size: 1 # 标签数量阈值，标签文章数需大于该值时才标记为特色标签

# 渐进式网页应用（PWA）设置
chrome-tab-theme-color: "#000000" # Chrome 标签页主题颜色
service-worker: true # 是否启用 Service Worker（PWA支持）

# 带数学公式页面的 MathJax 渲染设置
page-mathjax: false # 是否启用 MathJax，用于数学公式渲染

# 友情链接设置
friends:
  [
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
